### PR TITLE
Update config2015.ini

### PR DESCRIPTION
**Pull request by raghavrv**
Updated the blog rss feed url!

### CODE REVIEW

**Comment by rvraghav93** [comment]
Hey Terri! The site terri.toybox.ca/python-soc/ is not updated with my blog entry... Is there something else I should do about that?

**Comment by raghavrv** [comment]
Hey @terriko ! The site terri.toybox.ca/python-soc/ is not updated with my blog entry... Is there something else I should do about that?

**Comment by terriko** [comment]
There _shouldn't_ be, but it's possible that the updater script didn't pull the newest version of the config file for some reason. I will look into it, but it might not be until tomorrow (I have a concert tonight).

**Comment by raghavrv** [comment]
Oh! okay :) Have a great time :)

**Comment by terriko** [comment]
In case you didn't notice: this is fixed now.  I had a typo in the crontab script that was causing it to not sync correctly with github.  Thanks for helping find the bug!

**Comment by raghavrv** [comment]
thanks for updating :D

**Pull request merged**
